### ISSUE TITLE
Bug Report: Wallet always shows mainnet address

### ISSUE THREAD

**Issue by friedger** [cryptocracy/dapparatus#3]
**STX Pay Out Address:**
SP3AQDW78BWS2AZMBZWD7XWGH5HQS3HHVS2MC9NBD

Bug Description:
The Wallet -> Receive page always show the mainnet address, even though I switched to testnet

Replication Info:
1. See "Wrench" testnet icon on home page
2. Goto Wallet -> Receive
3. See SP.. address instead of ST.. address

**Comment by cryptocracy** [comment]
After thinking this over, it seems that the Wrench/Globe BTN to toggle between Networks would be pointless given the following:
- [x] Both Mainnet and Testnet addresses are presented on the Wallet -> Receive page 
- [x] Both Mainnet and Testnet addresses tx history is on the History page.
- [x] There is a Mainnet check field option on the Wallet -> Send page 
- [ ] Minting Respects Selected Network (TBD)
- [ ] Likely additional things yet to be determined. (TBD)

**Thanks for the Report!**  I'll be updating this accordingly.
**Payments:**
10 STX for Payout: 0xff5c0f77280cd4c74cda7299627af0d4c86517b9d02a1d5a21263070b003ae4f
1 STX for Payout: 0x344edad7d185cec487f0e80b609e6d59f1e5fcd12f0c58c9efad17a054431073
9 STX for Payout: 0xee44e71e8843f507af831546678231aa9872af1e319340d3348ebbfd6d7291fc

**Comment by cryptocracy** [comment]
this is ok to close, the additional concerns should sort themselves out during beta.
refer to [Beta Milestone](https://github.com/cryptocracy/dapparatus/milestone/2) for additional information.
